/**
 * fields.test.js — run with: node test/fields.test.js
 * Integrity of the generated field catalogue (js/fields.js).
 */
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const F = require('../js/fields.js');
const P = require('../js/protocol.js');

let passed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log(`  ok - ${name}`); }
  catch (err) { console.error(`  FAIL - ${name}\n    ${err.stack}`); process.exitCode = 1; }
}
const TYPES = new Set(['U8', 'U16', 'U32', 'S8', 'S16', 'S32', 'F32', 'F64', 'UTF-8', 'US-ASCII', 'HEX']);
const entries = Object.entries(F.FIELDS);

console.log('fields (generated catalogue)\n');

test('the catalogue has all 299 fields from the source table', () => {
  assert.strictEqual(F.COUNT, 299);
  assert.strictEqual(entries.length, 299);
});

test('every entry has a 6-hex-digit code, a sane length, a known type and a source set', () => {
  for (const [name, f] of entries) {
    assert.ok(/^[0-9A-F]{6}$/.test(f.code), `${name}: bad code ${f.code}`);
    assert.ok(Number.isInteger(f.len) && f.len >= 1 && f.len <= 255, `${name}: bad length ${f.len}`);
    assert.ok(TYPES.has(f.type), `${name}: unknown type ${f.type}`);
    assert.ok(f.set === 'generic' || f.set === 'kick', `${name}: bad set`);
  }
});

test('fixed-size types have the right length', () => {
  const size = { U8: 1, S8: 1, U16: 2, S16: 2, U32: 4, S32: 4, F32: 4, F64: 8 };
  for (const [name, f] of entries) if (size[f.type]) assert.strictEqual(f.len, size[f.type], `${name} (${f.type})`);
});

test('codes are unique, and BY_CODE maps every code back to a field with that code', () => {
  assert.strictEqual(new Set(entries.map(([, f]) => f.code)).size, 299);
  for (const [code, name] of Object.entries(F.BY_CODE)) assert.strictEqual(F.FIELDS[name].code, code);
  assert.strictEqual(Object.keys(F.BY_CODE).length, 299);
});

test('the dashboard\'s small verified field set agrees exactly with the catalogue', () => {
  for (const [name, spec] of Object.entries(P.FIELDS)) {
    const f = F.FIELDS[name];
    assert.ok(f, `${name} missing from the catalogue`);
    assert.deepStrictEqual({ code: f.code, len: f.len, type: f.type }, { code: spec.code, len: spec.len, type: spec.type }, name);
  }
});

test('the generated file records where it came from and says not to edit it', () => {
  const src = fs.readFileSync(path.join(__dirname, '..', 'js', 'fields.js'), 'utf8');
  assert.match(src, /GENERATED by tools\/gen_fields\.py/);
  assert.match(src, /sha256: [0-9a-f]{64}/);
  assert.match(src, /BaesTheorem\/niu-kqi/);
});

test('every type used by the catalogue can be decoded', () => {
  for (const type of new Set(entries.map(([, f]) => f.type))) {
    const len = { U8: 1, S8: 1, U16: 2, S16: 2, U32: 4, S32: 4, F32: 4, F64: 8 }[type] || 3;
    assert.doesNotThrow(() => P.decodeValue({ type, len }, new Uint8Array(len)), type);
  }
});

console.log(`\n${passed} passed`);
