#!/usr/bin/env python3
"""
Generates js/fields.js — the catalogue of every field the NIU protocol knows about —
from data/fields.json in https://github.com/BaesTheorem/niu-kqi (MIT; see NOTICE.md).

Usage:  python3 tools/gen_fields.py /path/to/niu-kqi/data/fields.json > js/fields.js

Kick-scooter fields (foc_k_*, db_k_*) win over shared fields on a name or code clash,
matching the reference implementation.
"""
import hashlib, json, sys

path = sys.argv[1]
raw = open(path, 'rb').read()
table = json.loads(raw)
digest = hashlib.sha256(raw).hexdigest()

fields = {}
for n, s in table['generic'].items():
    fields[n] = (s['code'].upper(), s['len'], s['type'], 'generic')
for n, s in table['kconfig'].items():
    fields[n] = (s['code'].upper(), s['len'], s['type'], 'kick')

lines = []
for name in sorted(fields):
    code, ln, typ, src = fields[name]
    lines.append(f"    {name}: {{ code: '{code}', len: {ln}, type: '{typ}', set: '{src}' }},")

print(f"""/**
 * fields.js — NIU Companion Web Dashboard
 *
 * GENERATED by tools/gen_fields.py — do not edit by hand.
 *
 * Every field the NIU protocol knows about: a 3-byte code, a length and a type.
 * Extracted from NIU's app by https://github.com/BaesTheorem/niu-kqi (MIT, see NOTICE.md).
 * source data/fields.json sha256: {digest}
 *
 * Being listed here does NOT mean a given scooter answers it: many belong to other models,
 * and a KQi 200F refuses those. The Diagnostics tool exists to find out which it answers.
 * Fields from the 'kick' set take precedence over 'generic' ones on a clash.
 */
(function (root, factory) {{
  if (typeof module === 'object' && module.exports) {{
    module.exports = factory();
  }} else {{
    root.NIU = root.NIU || {{}};
    root.NIU.Fields = factory();
  }}
}})(typeof self !== 'undefined' ? self : this, function () {{
  const FIELDS = {{
{chr(10).join(lines)}
  }};

  // code -> field name (kick-scooter set wins on a clash, as in FIELDS above)
  const BY_CODE = {{}};
  for (const name of Object.keys(FIELDS)) {{
    const f = FIELDS[name];
    if (!BY_CODE[f.code] || f.set === 'kick') BY_CODE[f.code] = name;
  }}

  return {{ FIELDS, BY_CODE, COUNT: Object.keys(FIELDS).length }};
}});""")
print(f"{len(fields)} fields, source sha256 {digest}", file=sys.stderr)
